namespace: backend
replicaCount: 2

image:
  repository: ghcr.io/YOUR_GITHUB_ORG/order-service
  tag: "latest"
  pullPolicy: IfNotPresent

port: 8000

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "400m"
    memory: "384Mi"

env:
  MONGO_DB_NAME: "orderdb"
  AUTH_SERVICE_URL: "http://auth-service.backend.svc.cluster.local:3001"
  PRODUCT_SERVICE_URL: "http://product-service.backend.svc.cluster.local:3002"

secrets:
  mongoUri: "mongodb://orderuser:orderpass@order-mongodb-0.order-mongodb-headless.database.svc.cluster.local:27017/orderdb"
  jwtSecret: "CHANGE_ME_JWT_SECRET_MIN_32_CHARS_LONG"
