namespace: backend
replicaCount: 2

image:
  repository: ghcr.io/YOUR_GITHUB_ORG/auth-service
  tag: "latest"
  pullPolicy: IfNotPresent

port: 3001

service:
  type: ClusterIP
  port: 3001

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "400m"
    memory: "384Mi"

env:
  PORT: "3001"
  NODE_ENV: "production"
  MONGO_DB_NAME: "authdb"

secrets:
  mongoUri: "mongodb://authuser:authpass@auth-mongodb-0.auth-mongodb-headless.database.svc.cluster.local:27017/authdb"
  jwtSecret: "CHANGE_ME_JWT_SECRET_MIN_32_CHARS_LONG"
