namespace: frontend
replicaCount: 2

image:
  repository: ghcr.io/YOUR_GITHUB_ORG/shopmesh-frontend
  tag: "latest"
  pullPolicy: IfNotPresent

port: 80

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

env:
  REACT_APP_AUTH_URL: "http://auth-service.backend.svc.cluster.local:3001"
  REACT_APP_PRODUCT_URL: "http://product-service.backend.svc.cluster.local:3002"
  REACT_APP_ORDER_URL: "http://order-service.backend.svc.cluster.local:8000"
