# Default values — override per release (auth-mongodb, product-mongodb, order-mongodb)
fullname: auth-mongodb
ownerService: auth-service

image:
  repository: mongo
  tag: "7.0"
  pullPolicy: IfNotPresent

auth:
  user: authuser
  password: authpass
  database: authdb

storage:
  size: 5Gi
  storageClassName: nfs-storage

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
