apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: {{ .Values.namespace | default "backend" }}
  labels:
    app: auth-service
type: Opaque
data:
  MONGO_URI: {{ .Values.secrets.mongoUri | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
